# Generated by Django 5.2.7 on 2025-10-06 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_manual', models.TextField(blank=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('horas_reportadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_aprobacion', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.actividad')),
                ('administrador_aprobo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_aprobados', to=settings.AUTH_USER_MODEL)),
                ('becario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_horas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
