# Generated by Django 5.2.7 on 2025-10-06 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('Interna', 'Voluntariado Interno'), ('Externa', 'Voluntariado Externo'), ('Taller', 'Taller'), ('Chat', 'Chat de Inglés')], max_length=20)),
                ('fecha', models.DateField()),
                ('duracion_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('competencia_desarrollada', models.CharField(blank=True, max_length=100)),
                ('modalidad', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], max_length=1)),
                ('organizacion', models.CharField(blank=True, max_length=100)),
                ('facilitador', models.CharField(blank=True, max_length=100)),
                ('en_catalogo', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
