# Generated by Django 5.2.7 on 2025-11-08 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='becarios_asignados',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'becario'}, related_name='actividades_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
