# Generated by Django 5.2.7 on 2025-11-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_actividad_becarios_asignados'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar'),
        ),
    ]
