# Generated by Django 5.2.7 on 2025-10-06 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(max_length=20)),
                ('horas_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horas_alcanzadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('becario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('becario', 'tipo_actividad')},
            },
        ),
    ]
