# Generated by Django 5.0.6 on 2025-11-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='configuracion_inicial_completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pregunta_seguridad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='respuesta_seguridad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
