# Generated by Django 5.2.7 on 2025-11-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_managers_alter_usuario_is_active'),
        ('users', '0002_usuario_configuracion_inicial_completada_and_more'),
    ]

    operations = [
    ]
